spring:
  application:
    name: mylittleapp
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health