spring:
  application:
    name: mylittleapp
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
  threads:
    virtual:
      enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 10MB
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health
base:
  url: "http://localhost:8080"